### ISSUE TITLE
API spec

### ISSUE THREAD

**Issue by zuse-z3** [mindtastic/mood-diary#11]
While checking the current state of the endpoints we need to change the specification:

- [x] GET /diary getAllEntries, return all entries {id, mood_day, mood_type, mood_descr}
- [x] GET /diary/:id getEntryById, return mood entry  {id, mood_day, mood_type, mood_descr}
- [x] POST /diary create mood entry  {mood_day, mood_type, mood_descr}, returns 201 Created 
- [x] DELETE /diary/:id , delete mood entry by id, returns  204 No Content
- [x] PUT /diary/:id, update mood entry by id returns 204 No Content

**Comment by jgraeger** [comment]
Decision: 
- Use ISO 8601 as format for datetime (mood_day) strings, as it's the *native* javascript date encoding.
- `PUT` endpoint returns `204 - No Content` on success as all relevant data is already known by the user.

**Comment by jgraeger** [comment]
@zuse168 Please change the POST endpoint to return `201 Created` and the DELETE endpoint to return `204 No Content` as well.
