### ISSUE TITLE
Default express handler returns HTML instead of JSON

### ISSUE THREAD

**Issue by jgraeger** [mindtastic/mood-diary#22]
## Description

We implemented that all occurring handlers will be handled by the express default middleware (except `sequelize.ValidationError` which gets handled by our own error handling middleware). Unfortunately, the express middleware always return HTML, even if `Accept: application/json` is sent. As our API is completely JSON based, we want to always return JSON to the user.

## Proposed fix

Write an own default error handling middleware, that returns a a corresponding status code (I assume we have to handle `404 Not Found` and all other errors as `500 Internal server error`). Depending on the error, we could return the `JSON.stringify()` of the error, but keep in mind, that errors could contain sensitive data.

## Example
```bash
curl -v http://localhost:8888 \
    -H 'X-User-Id:c305d645-1273-4022-a69f-fcccb9261ec9' \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' 

*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET / HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.79.1
> X-User-Id:c305d645-1273-4022-a69f-fcccb9261ec9
> Accept: application/json
> Content-Type: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 139
< Date: Wed, 06 Jul 2022 07:01:14 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
* Connection #0 to host localhost left intact
```

**Comment by romanyg** [comment]
I just fixed it in #25
